import { writeFile } from "node:fs/promises";
import { join } from "node:path";

export async function createMockPiScript(rootDir: string): Promise<string> {
  const scriptPath = join(rootDir, "mock-pi-rpc.mjs");
  const script = [
    "import { randomUUID } from 'node:crypto';",
    "import { writeFile } from 'node:fs/promises';",
    "import { StringDecoder } from 'node:string_decoder';",
    "import { join } from 'node:path';",
    "",
    "const sessionDirFlag = process.argv.indexOf('--session-dir');",
    "const sessionDir = process.argv[sessionDirFlag + 1] ?? process.argv[2] ?? process.cwd();",
    "const capturePath = process.env.CODAPTER_CAPTURE_PROCESS_PATH;",
    "const decoder = new StringDecoder('utf8');",
    "let buffer = '';",
    "let promptCounter = 0;",
    "",
    "const state = {",
    "  sessionId: 'mock-session',",
    "  sessionFile: undefined,",
    "  sessionName: undefined,",
    "  model: { provider: 'pi', id: 'mock-default', name: 'Mock Default', reasoning: true, input: ['text', 'image'], contextWindow: 128000 },",
    "  history: [],",
    "  lastElicitationResponse: undefined,",
    "  tokens: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },",
    "};",
    "",
    "const availableModels = [",
    "  { provider: 'pi', id: 'mock-default', name: 'Mock Default', reasoning: true, input: ['text', 'image'], contextWindow: 128000 },",
    "  { provider: 'pi', id: 'mock-fast', name: 'Mock Fast', reasoning: false, input: ['text'], contextWindow: 64000 },",
    "  { provider: 'openai-codex', id: 'gpt-5.3-codex', name: 'GPT-5.3 Codex', reasoning: true, input: ['text', 'image'], contextWindow: 272000 },",
    "  { provider: 'anthropic', id: 'claude-opus-4-6', name: 'Claude Opus 4.6', reasoning: true, input: ['text', 'image'], contextWindow: 1000000 },",
    "];",
    "",
    "if (capturePath) {",
    "  await writeFile(capturePath, JSON.stringify({",
    "    pid: process.pid,",
    "    argv: process.argv.slice(2),",
    "    cwd: process.cwd(),",
    "    collabSocketPath: process.env.CODAPTER_COLLAB_UDS ?? null,",
    "    parentThreadId: process.env.CODAPTER_COLLAB_PARENT_THREAD ?? null,",
    "    availableModelsDescription: process.env.CODAPTER_COLLAB_AVAILABLE_MODELS_DESCRIPTION ?? null,",
    "  }), 'utf8');",
    "}",
    "",
    "function write(value) {",
    "  process.stdout.write(JSON.stringify(value) + '\\n');",
    "}",
    "",
    "function response(id, command, data) {",
    "  write({ id, type: 'response', command, success: true, ...(data === undefined ? {} : { data }) });",
    "}",
    "",
    "function error(id, command, message) {",
    "  write({ id, type: 'response', command, success: false, error: message });",
    "}",
    "",
    "function clone(value) {",
    "  return JSON.parse(JSON.stringify(value));",
    "}",
    "",
    "function ensureSessionFile() {",
    "  if (!state.sessionFile) {",
    "    state.sessionFile = join(sessionDir, state.sessionId + '.jsonl');",
    "  }",
    "  return state.sessionFile;",
    "}",
    "",
    "function emitPromptTurn(message) {",
    "  if (process.env.CODAPTER_MOCK_RETRY) {",
    "    delete process.env.CODAPTER_MOCK_RETRY;",
    "    write({ type: 'message_end', message: { role: 'assistant', content: [], stopReason: 'error', errorMessage: 'Transient provider failure' } });",
    "    write({ type: 'agent_end', messages: [] });",
    "    setTimeout(() => emitPromptTurn(message), 80);",
    "    return;",
    "  }",
    "  const turnId = ++promptCounter;",
    "  const assistantToolMessage = {",
    "    id: 'assistant-tool-' + turnId,",
    "    role: 'assistant',",
    "    content: [{ type: 'toolCall', id: 'tool-' + turnId, name: 'bash', arguments: { command: 'echo hi' } }],",
    "    stopReason: 'toolUse',",
    "    timestamp: Date.now(),",
    "  };",
    "  const toolResultMessage = {",
    "    id: 'tool-result-' + turnId,",
    "    role: 'toolResult',",
    "    toolCallId: 'tool-' + turnId,",
    "    toolName: 'bash',",
    "    content: [{ type: 'text', text: 'hi' }],",
    "    isError: false,",
    "    timestamp: Date.now(),",
    "  };",
    "  const assistantFinalMessage = {",
    "    id: 'assistant-' + turnId,",
    "    role: 'assistant',",
    "    content: [{ type: 'text', text: 'response-' + turnId }],",
    "    stopReason: 'stop',",
    "    timestamp: Date.now(),",
    "  };",
    "  const userMessage = {",
    "    id: 'user-' + turnId,",
    "    role: 'user',",
    "    content: [{ type: 'text', text: message }],",
    "    timestamp: Date.now(),",
    "  };",
    "",
    "  state.history.push(userMessage);",
    "",
    "  setTimeout(() => {",
    "    write({ type: 'turn_start' });",
    "    write({ type: 'message_start', message: userMessage });",
    "    write({ type: 'message_end', message: userMessage });",
    "    write({ type: 'message_start', message: assistantToolMessage });",
    "    write({ type: 'message_end', message: assistantToolMessage });",
    "    write({",
    "      type: 'tool_execution_start',",
    "      toolCallId: 'tool-' + turnId,",
    "      toolName: 'bash',",
    "      args: { command: 'echo hi' },",
    "    });",
    "    write({",
    "      type: 'tool_execution_update',",
    "      toolCallId: 'tool-' + turnId,",
    "      toolName: 'bash',",
    "      args: { command: 'echo hi' },",
    "      partialResult: { content: [{ type: 'text', text: 'hi' }], details: { chunk: 1 } },",
    "    });",
    "    write({",
    "      type: 'tool_execution_end',",
    "      toolCallId: 'tool-' + turnId,",
    "      toolName: 'bash',",
    "      result: { content: [{ type: 'text', text: 'hi' }], details: { exitCode: 0 } },",
    "      isError: false,",
    "    });",
    "    write({",
    "      type: 'extension_ui_request',",
    "      id: 'elicitation-' + turnId,",
    "      method: 'confirm',",
    "      title: 'Confirm',",
    "      message: 'Proceed?',",
    "    });",
    "    write({ type: 'message_start', message: toolResultMessage });",
    "    write({ type: 'message_end', message: toolResultMessage });",
    "    write({ type: 'turn_end', message: assistantToolMessage, toolResults: [toolResultMessage] });",
    "    write({ type: 'turn_start' });",
    "    write({ type: 'message_start', message: assistantFinalMessage });",
    "    write({",
    "      type: 'message_update',",
    "      message: assistantFinalMessage,",
    "      assistantMessageEvent: { type: 'text_delta', delta: 'response-' + turnId },",
    "    });",
    "    write({ type: 'message_end', message: assistantFinalMessage });",
    "    write({ type: 'turn_end', message: assistantFinalMessage, toolResults: [] });",
    "    state.history.push(assistantToolMessage);",
    "    state.history.push(toolResultMessage);",
    "    state.history.push(assistantFinalMessage);",
    "    state.tokens = { input: 5, output: 7, cacheRead: 0, cacheWrite: 0, total: 12 };",
    "    write({ type: 'agent_end', messages: [assistantFinalMessage] });",
    "    setTimeout(() => write({ type: 'agent_settled' }), Number(process.env.CODAPTER_MOCK_SETTLE_DELAY ?? 0));",
    "  }, 15);",
    "}",
    "",
    "function handleCommand(command) {",
    "  const { id, type } = command;",
    "",
    "  if (type === 'get_state') {",
    "    response(id, 'get_state', {",
    "      sessionId: state.sessionId,",
    "      sessionFile: state.sessionFile,",
    "      sessionName: state.sessionName,",
    "      model: state.model,",
    "      thinkingLevel: state.thinkingLevel,",
    "    });",
    "    return;",
    "  }",
    "",
    "  if (type === 'new_session') {",
    "    if (process.env.CODAPTER_MOCK_CANCEL_NEW) { response(id, type, { cancelled: true }); return; }",
    "    state.sessionId = 'mock-' + randomUUID();",
    "    state.sessionFile = join(sessionDir, state.sessionId + '.jsonl');",
    "    response(id, 'new_session', { cancelled: false });",
    "    return;",
    "  }",
    "",
    "  if (type === 'switch_session') {",
    "    state.sessionFile = command.sessionPath;",
    "    response(id, 'switch_session', { cancelled: false });",
    "    return;",
    "  }",
    "",
    "  if (type === 'clone') {",
    "    state.sessionId = 'mock-' + randomUUID();",
    "    state.sessionFile = (state.sessionFile ?? join(sessionDir, 'forked.jsonl')) + '.fork';",
    "    response(id, 'clone', { cancelled: false });",
    "    return;",
    "  }",
    "",
    "  if (type === 'get_fork_messages') {",
    "    const anchor = state.history.filter((message) => message.role === 'user').at(-1);",
    "    response(id, 'get_fork_messages', {",
    "      messages: [{ entryId: anchor?.id ?? 'entry-1', text: anchor?.content?.text ?? 'anchor' }],",
    "    });",
    "    return;",
    "  }",
    "",
    "  if (type === 'set_session_name') {",
    "    state.sessionName = command.name;",
    "    response(id, 'set_session_name');",
    "    return;",
    "  }",
    "",
    "  if (type === 'set_model') {",
    "    const nextModel = availableModels.find((model) => model.provider === command.provider && model.id === command.modelId);",
    "    if (!nextModel) {",
    "      error(id, 'set_model', 'Model not found: ' + command.provider + '/' + command.modelId);",
    "      return;",
    "    }",
    "    state.model = nextModel;",
    "    response(id, 'set_model', { model: nextModel });",
    "    return;",
    "  }",
    "",
    "  if (type === 'set_thinking_level') {",
    "    state.thinkingLevel = command.level;",
    "    response(id, type);",
    "    return;",
    "  }",
    "",
    "  if (type === 'get_available_thinking_levels') { response(id, type, { levels: ['off','minimal','low','medium','high','xhigh','max'] }); return; }",
    "  if (type === 'get_available_models') {",
    "    response(id, 'get_available_models', { models: availableModels });",
    "    return;",
    "  }",
    "",
    "  if (type === 'get_messages') {",
    "    response(id, 'get_messages', { messages: clone(state.history) });",
    "    return;",
    "  }",
    "",
    "  if (type === 'get_session_stats') {",
    "    response(id, 'get_session_stats', {",
    "      sessionFile: state.sessionFile,",
    "      sessionId: state.sessionId,",
    "      userMessages: state.history.filter((message) => message.role === 'user').length,",
    "      assistantMessages: state.history.filter((message) => message.role === 'assistant').length,",
    "      toolCalls: 1,",
    "      toolResults: 1,",
    "      totalMessages: state.history.length,",
    "      tokens: state.tokens,",
    "      cost: 0,",
    "    });",
    "    return;",
    "  }",
    "",
    "  if (type === 'prompt') {",
    "    if (process.env.CODAPTER_MOCK_EXIT_ON_PROMPT) { process.exit(7); }",
    "    if (process.env.CODAPTER_MOCK_REJECT_PROMPT) { error(id, type, 'Rejected prompt'); return; }",
    "    if (process.env.CODAPTER_MOCK_HANDLED_PROMPT) { response(id, type, { disposition: 'handled' }); return; }",
    "    response(id, 'prompt');",
    "    emitPromptTurn(command.message);",
    "    return;",
    "  }",
    "",
    "  if (type === 'abort') {",
    "    response(id, 'abort');",
    "    return;",
    "  }",
    "",
    "  if (type === 'extension_ui_response') {",
    "    state.lastElicitationResponse = command;",
    "    state.history.push({",
    "      id: 'elicitation-response-' + Date.now(),",
    "      role: 'system',",
    "      content: clone(command),",
    "      timestamp: Date.now(),",
    "    });",
    "    return;",
    "  }",
    "",
    "  error(id, type, 'Unsupported command: ' + type);",
    "}",
    "",
    "process.stdin.setEncoding('utf8');",
    "process.stdin.on('data', (chunk) => {",
    "  buffer += chunk;",
    "  while (true) {",
    "    const newlineIndex = buffer.indexOf('\\n');",
    "    if (newlineIndex === -1) {",
    "      break;",
    "    }",
    "",
    "    const line = buffer.slice(0, newlineIndex).trim();",
    "    buffer = buffer.slice(newlineIndex + 1);",
    "    if (!line) {",
    "      continue;",
    "    }",
    "",
    "    try {",
    "      handleCommand(JSON.parse(line));",
    "    } catch (error) {",
    "      write({ type: 'response', command: 'unknown', success: false, error: error instanceof Error ? error.message : String(error) });",
    "    }",
    "  }",
    "});",
  ].join("\n");

  await writeFile(scriptPath, script, "utf8");
  return scriptPath;
}

export async function createModelProbeScript(rootDir: string): Promise<string> {
  const scriptPath = join(rootDir, "mock-pi-models-only.mjs");
  const script = [
    "import { writeFile } from 'node:fs/promises';",
    "import { StringDecoder } from 'node:string_decoder';",
    "",
    "const capturePath = process.env.CODAPTER_CAPTURE_PROCESS_PATH;",
    "const decoder = new StringDecoder('utf8');",
    "let buffer = '';",
    "",
    "if (capturePath) {",
    "  await writeFile(capturePath, process.pid + '\\n', { flag: 'a' });",
    "}",
    "",
    "function write(value) {",
    "  process.stdout.write(JSON.stringify(value) + '\\n');",
    "}",
    "",
    "function response(id, command, data) {",
    "  write({ id, type: 'response', command, success: true, ...(data === undefined ? {} : { data }) });",
    "}",
    "",
    "process.stdin.on('data', (chunk) => {",
    "  buffer += decoder.write(chunk);",
    "  const lines = buffer.split('\\n');",
    "  buffer = lines.pop() ?? '';",
    "  for (const line of lines) {",
    "    if (!line.trim()) continue;",
    "    const command = JSON.parse(line);",
    "    if (command.type === 'get_state') {",
    "      response(command.id, 'get_state', {",
    "        sessionId: 'models-only',",
    "        sessionFile: null,",
    "        sessionName: null,",
    "        model: { provider: 'anthropic', id: 'claude-opus-4-6', name: 'Claude Opus 4.6', reasoning: true, input: ['text', 'image'], contextWindow: 1000000 },",
    "      });",
    "      continue;",
    "    }",
    "    if (command.type === 'get_available_thinking_levels') { response(command.id, command.type, { levels: ['off','minimal','low','medium','high'] }); continue; }",
    "    if (command.type === 'get_available_models') {",
    "      setTimeout(() => {",
    "        response(command.id, 'get_available_models', {",
    "          models: [",
    "            { provider: 'anthropic', id: 'claude-opus-4-6', name: 'Claude Opus 4.6', reasoning: true, input: ['text', 'image'], contextWindow: 1000000 },",
    "          ],",
    "        });",
    "      }, 50);",
    "    }",
    "  }",
    "});",
  ];
  await writeFile(scriptPath, `${script.join("\n")}\n`, "utf8");
  return scriptPath;
}

export async function waitFor<T>(predicate: () => T | undefined, timeoutMs = 3000): Promise<T> {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    const value = predicate();
    if (value !== undefined) {
      return value;
    }
    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  throw new Error("Timed out waiting for condition");
}
